### PR TITLE
Remove 10x issue templates

### PR DESCRIPTION
**Pull request by GaryGapinski**
These did not belong in upstream.

### CODE REVIEW

**Comment by wesley-dean-gsa** [comment]
Could we use some issue creation-tiggered logic that would perform some automation magic to modify issues?

**Comment by wesley-dean-gsa** [comment]
For example, suppose an issue template (form?) has an option to select GSA or 18F; if the issue shows up in the "other" project (e.g., an issue in the GSA project when the submitter chose 18F), close the issue out?

**Comment by danielnaab** [comment]
That's interesting, but sounds a bit complicated. Can't we just remove the templates when we're done with phase 4? I'm not sure deleting them is solving much of a problem, as long as things are labelled properly.

**Comment by wesley-dean-gsa** [comment]
> That's interesting, but sounds a bit complicated. Can't we just remove the templates when we're done with phase 4? I'm not sure deleting them is solving much of a problem, as long as things are labelled properly.

oh yeah, it's absolutely more complicated and a direct violation of KISS.

**Comment by danielnaab** [comment]
Created #572 to track this, and a [label for P4 closeout tasks](https://github.com/18F/fedramp-automation/labels/closeout-p4).

**Comment by danielnaab** [comment]
Superseded by GSA pull request: https://github.com/GSA/fedramp-automation/pull/367

**Pull request closed without merging**
