### PR TITLE
Formatting, Text, and Scenario changes for ssp.xspec for scenario "For an OSCAL FedRAMP SSP"

### PR DESCRIPTION
**Pull request by markXLIX**
* Removed section scenarios
* Condensed some duplicative scenarios
* changed wording in scenario labels to be more readable
* changed expect-assert and expect-not-assert labels to be consistent

General formatting

### CODE REVIEW

**Review by danielnaab — APPROVED** [review]
:shipit:

**Comment by markXLIX** [comment]
Decision made by team not not complete this work due to lack of time at end of project.

**Comment by markXLIX** [comment]
reopened since the work was already complete for this section.

**Comment by markXLIX** [comment]
PR moved to GSA repo

**Pull request closed without merging**
