### PR TITLE
319 names of leveraged at os

### PR DESCRIPTION
**Pull request by markXLIX**
Test the compilation ATO list from FedRAMP against leveraged identifiers and titles.

Also updated the template slightly to allow for comparison of actual titles.

This one is a little more complicated and I'm not certain all aspects are accounted for.

### CODE REVIEW

**Review by GaryGapinski — COMMENTED** [review]
I am seeing some odd things here.

If I do a fresh clone of the repository, perform the submodule initialization, and then check out the `319-Names-of-Leveraged-ATOs` branch, the changes to `src/content/templates/ssp/xml/FedRAMP-SSP-OSCAL-Template.xml` are not visible. Can you duplicate?

The formatting appears to not match the agreed-upon line length of 150, and the indentation seems different as well. Examples in `src/validations/rules/ssp.sch` are lines [535-540](https://github.com/18F/fedramp-automation/blob/319-Names-of-Leveraged-ATOs/src/validations/rules/ssp.sch#L535-L540) and lines [544-551](https://github.com/18F/fedramp-automation/blob/319-Names-of-Leveraged-ATOs/src/validations/rules/ssp.sch#L544-L551). I think this variant formatting can be seen in some of the other PRs.

We should get together to ensure we're using the same formatting.

**Comment by markXLIX** [comment]
I see the AWS GovCloud addition to the leveraging authorization when I open the branch.  

Sure we can discuss the formatting and how you set your oXygen instance to enforce it.  Just grab time on my schedule.

**Comment by GaryGapinski** [comment]
> I see the AWS GovCloud addition to the leveraging authorization when I open the branch.

What do you see when you observe your branch on GitHub, e.g. `FedRAMP-SSP-OSCAL-Template.xml` lines 509-513?

**Comment by markXLIX** [comment]
509-513 looks the same as my local branch copy.  The only change to the template was on lns 648-650.  It seems like you are looking for a change that I did not make and isn't required for the validation.

Perhaps we should meet to look at this and the other comment regarding formatting?

**Comment by markXLIX** [comment]
That's the develop branch.  The #381 branch "319_Names-Of-Leveraged-ATOs" has the changes around those lines.

I'm available after 3 today.  But it appears that you are updating the contributing document.  So once that is done I'll check to match up my setup to that and update all outstanding branches with those formatting points.

**Comment by markXLIX** [comment]
Please provide some feedback on these formatting changes before I move onto other outstanding PRs and a comprehensive edit of the develop branch formatting.  

Thanks.

**Comment by GaryGapinski** [comment]
> Please provide some feedback on these formatting changes before I move onto other outstanding PRs and a comprehensive edit of the develop branch formatting.

I cannot duplicate what you have obtained. What are you using to format and indent?
What I do get, e.g., is
```
            <sch:assert
                diagnostics="no-description-text-in-component-diagnostic"
                id="no-description-text-in-component"
                role="error"
                test="o:description/o:p/text()">A component must have a description with content. </sch:assert>
```
after a format and indent. Note the the ending element tag is immediately after the text node(s). A whitespace was left, which will cause `sch.sch` to indicate a missing period at the end of the message (but normally there would be no whitespace because the ending element tag would not have been displaced).

I am available after 1145am ET to go over this.

**Comment by markXLIX** [comment]
I am using oXygen.  I did not do a global indent and format but rather went to the specific changes made for this PR and adjusted them to match the new formatting requirements in the contributing.md.

So, the assert above was not touched since it was not touched in this PR.

My plan is to fix these formatting issues in each outstanding PR and then, once those are merged, create a new PR to fix the formatting of remaining change.  This will include both PRs I've done since starting and any formatting that was outside the requirements from before.

We can discuss methods of global formatting within oXygen when we meet this afternoon.

**Comment by GaryGapinski** [comment]
Can you duplicate the following (note the ending element tag adjacent to text, and indentation within XPath).
```            <sch:assert
                diagnostics="has-public-cloud-deployment-model-diagnostic"
                id="has-public-cloud-deployment-model"
                role="error"
                test="
                    (: either there is no component or inventory-item tagged as 'public' :)
                    not(
                    exists(//oscal:component[oscal:prop[@name eq 'public' and @value eq 'yes']])
                    or
                    exists(//oscal:inventory-item[oscal:prop[@name eq 'public' and @value eq 'yes']])
                    )
                    or (: a 'public-cloud' deployment model is employed :)
                    exists(oscal:prop[@name eq 'cloud-deployment-model' and @value eq 'public-cloud'])
                    ">When a FedRAMP SSP has public components or inventory items, a cloud deployment model of "public-cloud" must be
                employed.</sch:assert>
```

I just grabbed that at random from `ssp.sch`. However, you'll notice that the same formatting appears throughout the document.

**Comment by markXLIX** [comment]
Duplicate it where?  That section of code already looks like that in this branch.

**Comment by markXLIX** [comment]
Let's try that update.  I think the breaking of lines for the some/satisfies is kind of arbitrary but I can get used to it.

**Review by GaryGapinski — APPROVED** [review]
Let's check XML formatting after this and other merges.

**Pull request merged**
