### PR TITLE
Add assertion views - grouping by business rules/documentation.

### PR DESCRIPTION
**Pull request by danielnaab**
Implementing #110, this branch adds the loading of "assertion views" (collections of assertion groups) from an XSLT-generated JSON document (#196), and updates the UI to display multiple assertion views.

Federalist link: https://federalist-2372d2fd-fc94-42fe-bcc7-a8af4f664a51.app.cloud.gov/preview/18f/fedramp-automation/one-pager/#/

### CODE REVIEW

**Review by ohsh6o — COMMENTED** [review]
@danielnaab Are the views in the `Select an assertion view` controlled by the JSON file? I presume since I do not see explicit references in code.

I think we should make those view names user friendly if we want to test them against our users. :-)

**Review by GaryGapinski — COMMENTED** [review]
This looks good overall.
Some observations:

- Hyperlinks in different areas have different renditions (FedRAMP|10x|Source code ones change with hover).
- The checklist references presume prior knowledge of the particular checklist used
- Since there are different numbers of assertions for each, perhaps the total number of concerns should change as view category changes?
- The upstream GSA `FedRAMP-SSP-OSCAL-Template.xml` has changed and should probably be copied to 18F.

**Comment by rrkane10x** [comment]
@danielnaab This looks great!

**Review by rrkane10x — APPROVED** [review]
Looks great!

**Pull request merged**
